export {Dummydata}
const Dummydata=[
    {
        
        sem1:{
            maths:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            physics:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            chemistry:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            BEEE:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
        },
        sem2:{
            English:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            DataScience:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            EVS:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            Maths:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
        },
        sem3:{
            AI:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            DBMS:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            Maths:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            C:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
            R:[
                {
                    name:'file1',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file2',
                    type:'pdf',
                    content:'xyz.pdf'
                },
                {
                    name:'file3',
                    type:'pdf',
                    content:'xyz.pdf'
                },
            ],
        },
        
        
    },
    
]

